### ISSUE TITLE
no numbers are shown

### ISSUE THREAD

**Issue by kostkrom** [arjo129/uSpeech#41]
I just installed my mic and μspeech. When i open serial monitor all are good but when i press a letter to calibrate nothing happens. I have connected my mic on A0. What am i doing wrong here?

**Comment by arjo129** [comment]
Have you checked which version you're using? https://arjo129.wordpress.com/2014/03/25/regarding-%C2%B5speech-4-1-2/

**Comment by kostkrom** [comment]
i am using 4.2 alpha

**Comment by arjo129** [comment]
Revert to  4.1.1 your issue will be fixed :package:

**Comment by kostkrom** [comment]
thank you... I want to ask you one more question. I ahve read all of your wiki and i didn't understarnd fully how the vocabulary of μspeech works. For example how i add the word light on on my code?

**Comment by arjo129** [comment]
You don't add words, it works using letters... In particular certain letters can be used as feedback. The term phoneme what is used in the wiki. Words are in the works and I should attend working on pushing them into mainline now.
