### ISSUE TITLE
LEDtest voice.calibrate() crashes on RePhone / Xadow

### ISSUE THREAD

**Issue by jonasrk** [arjo129/uSpeech#42]
Hey, great project!

I'm trying to run the LEDtest on my RePhone (Arduino compatible). It crashes during voice.calibrate() ... any thoughts on how to debug this?

Thanks!

**Comment by arjo129** [comment]
No idea... Could you point me to some docs

**Comment by arjo129** [comment]
What is the symptom of the "crash"
