### ISSUE TITLE
moving from arduino uno

### ISSUE THREAD

**Issue by mkeyno** [arjo129/uSpeech#43]
hi @arjo129  and thanks for your effort but I was wondering why don't you choose Arduino Uno module whereas almighty Arduino  ESP8266 is around , you have much speed and platy of flash to work with., Arduino 8bit AVR in kinda belong to museum , I hope you could change your course to ESP
BR

**Comment by arjo129** [comment]
I wrote this back in the days when there was no ESP8266. Perhaps when I get the time I can move it to an esp. I do think however ESP will be able to support more complicated algorithms.

**Comment by mkeyno** [comment]
very good choose @arjo129  , please let us know , I'm following your activity
BR
