### ISSUE TITLE
Please explain why it does not work

### ISSUE THREAD

**Issue by Pust0T** [arjo129/uSpeech#52]
The example is not compiled. (LEDTest)
Here is the error message

In file included from C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:11:0:

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.h:21:5: error: 'uint8_t' does not name a type

     uint8_t num_symbols;

     ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.h:24:11: error: 'uint8_t' does not name a type

     const uint8_t* words;

           ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.h:25:5: error: 'uint16_t' does not name a type

     uint16_t samples;

     ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.h:26:5: error: 'uint8_t' does not name a type

     uint8_t word_length;

     ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.h:29:22: error: 'uint8_t' has not been declared

     void set_symbols(uint8_t num);

                      ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.h:30:25: error: 'uint8_t' does not name a type

     void set_word(const uint8_t* word, uint8_t length);

                         ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.h:30:40: error: 'uint8_t' has not been declared

     void set_word(const uint8_t* word, uint8_t length);

                                        ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:18:34: error: variable or field 'set_symbols' declared void

 void ViterbiDecoder::set_symbols(uint8_t num){

                                  ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:18:34: error: 'uint8_t' was not declared in this scope

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:21:37: error: 'uint8_t' does not name a type

 void ViterbiDecoder::set_word(const uint8_t *word, uint8_t length){

                                     ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:21:52: error: 'uint8_t' has not been declared

 void ViterbiDecoder::set_word(const uint8_t *word, uint8_t length){

                                                    ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp: In member function 'void ViterbiDecoder::set_word(const int*, int)':

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:22:5: error: 'words' was not declared in this scope

     words = word;

     ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:23:5: error: 'word_length' was not declared in this scope

     word_length = length;

     ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:24:69: error: 'malloc' was not declared in this scope

     accumulated_probabilities =  (float*)malloc(length*sizeof(float));

                                                                     ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp: In member function 'void ViterbiDecoder::decode(float*)':

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:30:24: error: 'word_length' was not declared in this scope

     for(int i = 0; i < word_length; i++)

                        ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:32:25: error: 'word_length' was not declared in this scope

     for(int i = 0;  i < word_length-1; i++){

                         ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:33:51: error: 'words' was not declared in this scope

         new_probabilities[i] += classifier_output[words[i]]*accumulated_probabilities[i];

                                                   ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:36:23: error: 'word_length' was not declared in this scope

     new_probabilities[word_length-1] += classifier_output[words[word_length-1]]*accumulated_probabilities[word_length-1];

                       ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:36:59: error: 'words' was not declared in this scope

     new_probabilities[word_length-1] += classifier_output[words[word_length-1]]*accumulated_probabilities[word_length-1];

                                                           ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp: In member function 'void ViterbiDecoder::reset()':

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:41:5: error: 'samples' was not declared in this scope

     samples = 0;

     ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:42:24: error: 'num_symbols' was not declared in this scope

     for(int i = 0; i < num_symbols; i++) accumulated_probabilities[i] = 0;

                        ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp: In member function 'float ViterbiDecoder::get_probability()':

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:46:38: error: 'word_length' was not declared in this scope

     return accumulated_probabilities[word_length-1];

                                      ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\accumulator.cpp:24:36: error: no 'void Accumulator::to_probabilities()' member function declared in class 'Accumulator'

 void Accumulator::to_probabilities(){

                                    ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\signal.cpp: In member function 'signal::maxPower()':

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\signal.cpp:85:24: warning: iteration 31 invokes undefined behavior [-Waggressive-loop-optimizations]

         avgPower+=arr[i];

                        ^

C:\Users\Pust0T\Documents\Arduino\libraries\uSpeech-master\signal.cpp:79:13: note: containing loop

     while (i<32){

             ^

exit status 1
Ошибка компиляции для платы Arduino/Genuino Uno.

**Comment by Pust0T** [comment]
In the example and the library did not change anything

**Comment by arjo129** [comment]
Fixed
