### ISSUE TITLE
Compile Error!!

### ISSUE THREAD

**Issue by ViduraV-coder** [arjo129/uSpeech#56]
C:\Program Files (x86)\Arduino\libraries\uSpeech-master\accumulator.cpp:24:36: error: no 'void Accumulator::to_probabilities()' member function declared in class 'Accumulator'

 void Accumulator::to_probabilities(){

                                    ^

C:\Program Files (x86)\Arduino\libraries\uSpeech-master\viterbidecoder.cpp: In member function 'void ViterbiDecoder::set_word(const uint8_t*, uint8_t)':

C:\Program Files (x86)\Arduino\libraries\uSpeech-master\viterbidecoder.cpp:24:42: error: 'malloc' was not declared in this scope

     accumulated_probabilities =  (float*)malloc(length*sizeof(float));

                                          ^~~~~~

**Comment by skabbit** [comment]
Got the same error

**Comment by FrankBoesing** [comment]
Seems you have to use a better platform which supports malloc...

**Comment by arjo129** [comment]
Use the releases page
